stages:

  download_dataset:
    cmd: python src/download_file.py ${dataset.link} -o ${dataset.root}${dataset.archive}
    deps:
      - src/download_file.py
    params:
      - dataset.link
      - dataset.root
      - dataset.archive
    outs:
      - ${dataset.root}${dataset.archive}

  extract_dataset:
    cmd: unzip -n ${dataset.archive_root}${dataset.archive} -d ${dataset.root} > /dev/null
    deps:
      - ${dataset.root}${dataset.archive}
    params:
      - dataset.archive
      - dataset.archive_root
      - dataset.root      
      - dataset.name 
    outs:
      - ${dataset.root}${dataset.name}

  download_model:
    cmd: python src/download_file.py ${model.checkpoint_link} -o ${model.checkpoint_base}
    deps:
      - src/download_file.py
    outs:
      - ${model.checkpoint_base}

  get_base_model:
    cmd: python src/setup_model.py ${model.config_root}${model.name} ${model.config_workdir}${model.name} --no-modify
    params:
      - model.config_root
      - model.config_workdir
      - model.name
    outs:
      - ${model.config_workdir}${model.name}

  setup_detector:
    cmd: python src/setup_model.py ${model.config_workdir}${model.name} ${model.config_workdir}${model.new_name}
    deps:
      - ${model.config_workdir}${model.name}
      - src/setup_model.py
      - src/cfg_modification.py
    params:
      - model.config_workdir
      - model.name
      - model.new_name
    outs:
      - ${model.config_workdir}${model.new_name}

  train_model:
    cmd: python src/train.py ${model.config_workdir}${model.new_name}
    deps:
      - ${dataset.root}${dataset.name}
      - ${model.checkpoint_base}
      - ${model.config_workdir}${model.new_name}

#  test_detector:
#    cmd: python src/test.py ${model.config_workdir}${model.new_name} ${model.checkpoint}
#    deps:
#      - ${model.checkpoint}
